# linear-regression

Use the "Run" button to execute the code.

In [146]:
!pip install jovian --upgrade --quiet

In [147]:
import jovian

In [148]:
# Execute this to save new versions of the notebook
jovian.commit(project="linear-regression")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "anvith77/linear-regression" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/anvith77/linear-regression


'https://jovian.ai/anvith77/linear-regression'

In [149]:
# importing libraries 
import torch 
import numpy as np

In [150]:
# Data set's inputs (temperature,rainfall,humidty)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [151]:
# Targets (apples,oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [152]:
# converting a numpy matrix to a tensor for both targets and inputs 
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [153]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [154]:
# Randomly Assigning both Weights and Bias, Weight is a matrix and bias is a vector of dimention 
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad = True)

In [155]:
print(w)
print(b)

tensor([[ 0.5337, -1.6761,  0.5691],
        [-1.7540, -0.5356,  0.5033]], requires_grad=True)
tensor([-0.8621,  1.3306], requires_grad=True)


In [156]:
# defining a fucntion for the model that is wx + b , w is transposed
def model(x):
    return x @ w.t() + b 

In [157]:
# making a prediction using the model for the input 
preds = model(inputs)
print(preds)

# the target values 
print(targets)

#they are off by a larger margin 

tensor([[ -49.7334, -140.9551],
        [ -63.3751, -173.2058],
        [-146.0243, -193.8485],
        [   2.5543, -181.9846],
        [ -85.1097, -135.8840]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [158]:
# Calculating the mean squared error (MSE):
def mse(t1,t2):
    diff = t1-t2
    error = torch.sum(diff * diff)/diff.numel()
    return error 

# difference bwtween tensor t1 and t2 squaring the difference (to remove -ve values) and taking sum using torch.sum()
# dividing the overall obtained sum by the number of elements present in the tensor using numel() to get an average 

In [159]:
# mse for the predictions and targets 
loss = mse(preds,targets)
print(loss)

# each element differs from the target value by the sqrt(loss) 
# sqrt(47746.5938) is about 218 from the target value

tensor(47746.5938, grad_fn=<DivBackward0>)


In [160]:
# compute gradient 
#loss.backward()

# compute gradient of the weights 
#print(w)
#print(w.grad)

In [161]:
#w
#w.grad

In [162]:
'''
with torch.no_grad():
    w = -w.grad * 1e-5 
    b = -b.grad * 1e-5 
# no grad , so pytorch dosen't update/track while calculating weights and bias 
# 1e-5 is the learning rate 
'''

"\nwith torch.no_grad():\n    w = -w.grad * 1e-5 \n    b = -b.grad * 1e-5 \n# no grad , so pytorch dosen't update/track while calculating weights and bias \n# 1e-5 is the learning rate \n"

In [165]:
# Training for 200 epochs
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [166]:
loss = mse(preds,targets)
print(loss)

tensor(54.3009, grad_fn=<DivBackward0>)


In [167]:
# both the predicted and targeted values are very close
print(preds)
print(targets)

tensor([[ 59.4357,  70.0526],
        [ 87.4857, 102.5688],
        [103.0346, 129.0569],
        [ 35.4968,  34.4260],
        [102.5208, 124.2170]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
